"""Canonical Publication v1 and Phase 2C delivery boundary for DailyInfo.

The canonical models/finalizer/store remain transport-independent. Publisher
implementations are exposed separately so a sink consumes a validated
``PublicationBundle`` without becoming part of the publication model.
"""

from .adapters import (
    PublicationBriefingInput,
    PublicationItemInput,
    StructuredPublicationAdapter,
)
from .finalizer import PublicationFinalizer
from .identity import (
    normalize_arxiv_id,
    normalize_doi,
    normalize_external_id,
    normalize_repo_id,
    source_namespace,
)
from .models import (
    CANONICAL_CATEGORIES,
    SCHEMA_VERSION,
    Briefing,
    IdentityConflictError,
    Item,
    PublicationBundle,
    PublicationValidationError,
    SourceMetadata,
)
from .pipeline import (
    PublicationRunCollector,
    StructuredItemResult,
    StructuredResultError,
    now_utc,
    parse_structured_response,
    results_from_response,
    source_ref,
    structured_entries,
    structured_prompt,
)
from .serialization import (
    briefing_content_hash,
    bundle_content_hash,
    deserialize_bundle,
    item_content_hash,
    serialize_bundle,
)
from .store import (
    CorruptPublicationError,
    PublicationStore,
    PublicationStoreError,
    StoreResult,
)
from .delivery import (
    CorruptDeliveryStateError,
    DeliveryState,
    DeliveryStateStore,
    DeliveryStoreError,
    DeliveryValidationError,
    DELIVERY_SCHEMA_VERSION,
    delivery_key,
    delivery_state_from_dict,
    delivery_state_to_dict,
    serialize_delivery_state,
    validate_briefing_identity,
    validate_delivery_state,
    validate_sink,
)
from .publishers import (
    DeliveryCoordinator,
    DiscordPublisher,
    PublishResult,
    Publisher,
    sanitize_error,
)
from .web import (
    DEFAULT_WEB_BRANCH,
    DEFAULT_WEB_REMOTE,
    DEFAULT_WEB_VALIDATION_COMMANDS,
    WEB_SINK,
    WebPublishConfig,
    WebPublisher,
    WebPublishError,
    serialize_web_briefing,
    serialize_web_item,
)
from .validation import (
    validate_briefing,
    validate_bundle,
    validate_category,
    validate_item,
    validate_public_source_url,
)

__all__ = [
    "Briefing",
    "briefing_content_hash",
    "bundle_content_hash",
    "CANONICAL_CATEGORIES",
    "IdentityConflictError",
    "Item",
    "item_content_hash",
    "PublicationBriefingInput",
    "PublicationBundle",
    "PublicationFinalizer",
    "PublicationItemInput",
    "PublicationStore",
    "PublicationRunCollector",
    "PublicationStoreError",
    "PublicationValidationError",
    "SCHEMA_VERSION",
    "SourceMetadata",
    "StoreResult",
    "StructuredPublicationAdapter",
    "StructuredItemResult",
    "StructuredResultError",
    "CorruptPublicationError",
    "deserialize_bundle",
    "serialize_bundle",
    "source_namespace",
    "normalize_arxiv_id",
    "normalize_doi",
    "normalize_external_id",
    "normalize_repo_id",
    "source_ref",
    "structured_entries",
    "structured_prompt",
    "parse_structured_response",
    "results_from_response",
    "now_utc",
    "validate_briefing",
    "validate_bundle",
    "validate_category",
    "validate_item",
    "validate_public_source_url",
    "CorruptDeliveryStateError",
    "DELIVERY_SCHEMA_VERSION",
    "DeliveryCoordinator",
    "DeliveryState",
    "DeliveryStateStore",
    "DeliveryStoreError",
    "DeliveryValidationError",
    "DiscordPublisher",
    "PublishResult",
    "Publisher",
    "sanitize_error",
    "DEFAULT_WEB_BRANCH",
    "DEFAULT_WEB_REMOTE",
    "DEFAULT_WEB_VALIDATION_COMMANDS",
    "WEB_SINK",
    "WebPublishConfig",
    "WebPublisher",
    "WebPublishError",
    "serialize_web_briefing",
    "serialize_web_item",
    "delivery_key",
    "delivery_state_from_dict",
    "delivery_state_to_dict",
    "serialize_delivery_state",
    "validate_delivery_state",
    "validate_briefing_identity",
    "validate_sink",
]
